WebelopersMatchBackend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home.views import home, contact_us, contact_us_done

urlpatterns = [
    path('', home, name='home' ),
    path('contact_us/', contact_us, name='contact_us'),
    path('contact_us_done/', contact_us_done, name='contact_us_done'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from accounts.views import signup, logout_user, panel, create_item, AllProducts, edit, delete_product, \
    EntireProducts, product_page, rate, order, cart, cart_delete

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('signup/', signup, name='signup'),
    path('logout/', logout_user, name='logout'),
    path('panel/', panel, name='panel'),
    path('create_item/', create_item, name='create_item'),
    path('cart/<id>/', cart, name='cart'),
    path('cart/delete/<pk>/',cart_delete, name='cart_delete'),
    path('rate/<id>/<redirect_page>', rate, name='rate'),
    path("order/", order, name='order'),
    path('all_products/', AllProducts.as_view(), name='all_products'),
    path('entire_products/', EntireProducts.as_view(), name='entire_products'),
    path('edit/<id>/', edit, name='edit'),
    path('product/<id>/', product_page, name='product_page'),
    path('delete_product/<id>/', delete_product, name='delete_product'),

]

home/urls.py
from django.urls import path

from home.views import home, contact_us, contact_us_done

app_name = 'home'
urlpatterns = [
    path('', home, name='index'),



]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class Tag(models.Model):
    name = models.TextField()

    def __str__(self):
        return self.name


class Comment(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    text = models.TextField()


class Rate(models.Model):
    rate_number = models.PositiveBigIntegerField(default=0)


class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.TextField()
    quantity = models.IntegerField()
    price = models.IntegerField()
    tag = models.ManyToManyField(Tag)
    comments = models.ManyToManyField(Comment)
    product_image = models.ImageField(upload_to='images/', blank=True)
    rate = models.ManyToManyField(Rate)


    def __str__(self):
        return self.name


class ShoppingCard(models.Model):
    user = models.ManyToManyField(User)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    buy_quantity=models.IntegerField()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from accounts.models import Product


class SignUpForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'id': 'username'}))
    first_name = forms.CharField(required=False, help_text='Optional.',
                                 widget=forms.TextInput(attrs={'id': 'first_name'}))
    last_name = forms.CharField(required=False, help_text='Optional.',
                                widget=forms.TextInput(attrs={'id': 'last_name'}))
    email = forms.EmailField(help_text='Required. Inform a valid email address.',
                             widget=forms.TextInput(attrs={'id': 'email'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'id': 'password1'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'id': 'password2'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)


class CreateItemForm(forms.ModelForm):
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'name': 'name'}))
    quantity = forms.CharField(required=True, widget=forms.TextInput(attrs={'name': 'quantity'}))
    price = forms.CharField(required=True,
                            widget=forms.TextInput(attrs={'name': 'price'}))
    tag = forms.CharField(required=False, widget=forms.TextInput(attrs={'name': 'tag'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['product_image'].widget.attrs.update({'id': 'product_image'})


    def set_initial(self, name_text='', price_text=0, quantity_text=0):
        # self.name.initial = name_text
        # self.price.initial = price_text
        # self.quantity.initial = quantity_text
        pass

    class Meta:
        model = Product
        fields = ('name', 'quantity', 'price', 'tag', 'product_image', 'user', )
        widgets = {
            'user': forms.HiddenInput,
            # 'product_image':forms.FileField(widget=forms.ImageField(at))
            # 'comments': forms.HiddenInput(attrs={'required':False}),
            # 'tag': forms.HiddenInput(attrs={'required':False}),

        }

accounts/views.py
import sys

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group
from django.db.models import F, Q, Avg
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView

from accounts.forms import SignUpForm, CreateItemForm
from accounts.models import Product, Tag, ShoppingCard
from django.contrib import messages


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            raw_password2 = form.cleaned_data.get('password2')

            if raw_password != raw_password2:
                pass

            return redirect('home')

            # return HttpResponse("ok ")
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})


def logout_user(request):
    logout(request)
    return redirect(reverse('home'))


def panel(request):
    if request.method == 'POST':
        become_seller = False
        try:
            my_group = Group.objects.get(name='seller')
        except:
            my_group = Group.objects.create(name='seller')
            my_group.save()

        if request.user.groups.count() == 0:
            my_group.user_set.add(request.user)
            become_seller = True
        return render(request, 'accounts/panel.html',
                      {'has_msg': True, 'become_seller': become_seller, 'is_seller': True})

    is_seller = request.user.groups.count() > 0
    return render(request, 'accounts/panel.html', {'has_msg': False, 'is_seller': is_seller})


def create_item(request):
    if request.method == 'POST':
        data = request.POST.copy()
        data.update({'user': request.user, })
        form = CreateItemForm(data, request.FILES)
        if form.is_valid():
            # form.save()

            name = form.cleaned_data.get('name')
            quantity = int(form.cleaned_data.get('quantity'))
            price = int(form.cleaned_data.get('price'))
            tags = form.cleaned_data.get('tag')

            tag_names = tags.split(',')
            # Product.objects.create(user=request.user, name=name, quantity=quantity, price=price)
            product = Product(user=request.user, name=name, quantity=quantity, price=price)
            product.save()
            for tag in tag_names:
                # tag_count = Tag.objects.filter(name__exact=name).count()

                Tag.objects.get_or_create(name=tag)
                my_tag = Tag.objects.get(name=tag)
                print("TAAAG")
                print(my_tag)
                my_tag.save()
                product.tag.add(my_tag)

            product.save()

            # should fix

            return redirect('contact_us_done')

    else:
        form = CreateItemForm()
    return render(request, 'accounts/create-item.html', {'form': form})


def space_to_underline(string):
    return string.replace(' ', '_')


def get_link(obj):
    if obj:
        return obj.url

    return 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/330px-Image_created_with_a_mobile_phone.png'


def get_avg(rates):
    average = 0
    n = len(rates)
    if n > 0:
        sum = 0
        for rate in rates:
            sum += rate.rate_number
        return sum / n
    return average


class AllProducts(ListView):
    template_name = 'accounts/all_products.html'
    context_object_name = 'products'
    model = Product

    def get_queryset(self):
        products = Product.objects.filter(user=self.request.user)
        result = [(product.name, product.price, product.quantity,
                   space_to_underline(product.name) + "_" + product.user.username,
                   product.id,
                   product.tag.all(),
                   get_link(product.product_image),
                   get_avg(product.rate.all())) for product in products]
        # 0 : name
        # 1 : price
        # 2: quentity
        # 3: class name
        # 4: id
        # 5: tags
        # 6: image url
        # 7: rate avg
        return result


def edit(request, id):
    product = Product.objects.get(id=id)
    name = product.name
    price = product.price
    quantity = product.quantity

    if request.method == 'POST':

        data = request.POST.copy()
        data.update({'user': request.user, })
        # data.update({'user': request.user, 'comments': product.comments.all(), 'tag': product.tag.all()})
        form = CreateItemForm(data, request.FILES)
        if form.is_valid():
            # form.save()

            product.name = form.cleaned_data.get('name')
            product.quantity = int(form.cleaned_data.get('quantity'))
            product.price = int(form.cleaned_data.get('price'))
            product.product_image = form.cleaned_data.get('product_image')

            # should fix
            # Product.objects.create(user=request.user, name=name, quantity=quantity, price=price)
            product.save()
            return redirect('accounts:all_products')

    form = CreateItemForm()
    form.set_initial(name_text=name, price_text=price, quantity_text=quantity)
    # form.fields['name'].initil = 'name'
    return render(request, 'accounts/edit_product.html', {'form': form})


def delete_product(request, id):
    product = Product.objects.get(id=id)
    product.delete()
    return HttpResponse('ok')


class EntireProducts(ListView):
    template_name = 'accounts/enitre_products.html'
    context_object_name = 'products'
    model = Product

    def post(self, request):
        title = request.POST.get('title')
        min_price = request.POST.get('min_price')
        max_price = request.POST.get('max_price')
        tags = request.POST.get('tag').split(',')

        products = Product.objects.filter(name__contains=title)
        if max_price != '' or min_price != '':
            print("min price= ", min_price)
            print("max price= ", max_price)
            if min_price != '' and max_price != '':

                products = Product.objects.filter(
                    Q(price__gte=int(min_price)) & Q(price__lte=int(max_price)))

            elif min_price == '':
                products = Product.objects.filter(
                    Q(price__lte=int(max_price)))
            elif max_price == '':
                products = Product.objects.filter(
                    Q(price__gte=int(min_price)))

        if len(tags):
            res = Product.objects.filter(tag__name__in=tags)
            for item in res:
                if not products.get(name__exact=item.name):
                    products += item

        result = [(product.name, product.price, product.quantity,
                   space_to_underline(product.name) + "_" + product.user.username,
                   product.id,
                   product.user.first_name,
                   product.user.last_name,
                   product.tag.all(),
                   get_link(product.product_image),
                   get_avg(product.rate.all()),) for product in products]

        # 0 : name
        # 1 : price
        # 2: quentity
        # 3: class name
        # 4: id
        # 5: first name
        # 6: last name
        # 7: tag
        # 8: product image url
        # 9: rate avg
        return render(request, 'accounts/enitre_products.html', {'products': result})

    def get_queryset(self, ):

        products = Product.objects.all()
        result = [(product.name, product.price, product.quantity,
                   space_to_underline(product.name) + "_" + product.user.username,
                   product.id,
                   product.user.first_name,
                   product.user.last_name,
                   product.tag.all(),
                   get_link(product.product_image),
                   get_avg(product.rate.all())) for product in products]
        # 0 : name
        # 1 : price
        # 2: quentity
        # 3: class name
        # 4: id
        # 5: first name
        # 6: last name
        # 7: tag
        # 8: product image
        # 9: rate average
        return result


def product_page(request, id):
    product = Product.objects.get(id=id)
    comments = product.comments.all()

    if request.method == 'POST':
        text = request.POST.get('text')
        product.comments.create(text=text, user=request.user)
    product_image_url = get_link(product.product_image)
    return render(request, 'accounts/product_page.html',
                  {'product': product, 'comments': comments, 'product_image_url': product_image_url})


def rate(request, id, redirect_page):
    if request.method == 'POST':
        product = Product.objects.get(id=id)
        rate_num = request.POST.get('rate')
        product.rate.create(rate_number=rate_num)
        product.save()
        if redirect_page == '1':
            return redirect("accounts:entire_products")
        else:
            return redirect("accounts:all_products")

    return HttpResponse('fail')


def order(request):
    if request.method == "POST":
        order_type = request.POST.get('order_type')
        order = request.POST.get('order')

        print(order_type)
        print(order)

        prefix = '-' if order == 'desc' else ''
        global products
        if order_type == 'username':
            products = Product.objects.order_by(prefix + 'user__username')
        elif order_type == 'price':
            products = Product.objects.order_by(prefix + 'price')
        elif order_type == 'rate':
            # products = Product.objects.order_by(prefix + 'rate_average')
            Product.objects.annotate(avg_rate=Avg('rate__rate_number')).order_by(prefix + 'rate__rate_number')

accounts/templates/accounts/all_products.html
{% extends 'base/base.html' %}


{% block title %}
    all products
{% endblock %}

{% block content %}
    <div id="all_products">
        {% for product in products %}
            {#            class name#}
            <div class="{{ product.3 }}">
                <img src="{{ product.6 }}" id="product_image_{{ product.3 }}" name="product_image_{{ product.3 }}">

                <a href="{% url 'accounts:edit' product.4 %}" id="edit_{{ product.3 }}">edit</a>
                <a href="{% url 'accounts:delete_product' product.4 %}" id="delete_{{ product.3 }}">delete</a>
                {#            name#}
                <h4>{{ product.0 }}</h4>
                <div>
                    {#                    price#}
                    {{ product.1 }}
                </div>
                <div>
                    {#                    quentity#}
                    {{ product.2 }}
                </div>
                {#            tags#}
                <div>
                    {% for tag in product.5 %}
                        <h4>
                            {{ tag.name }}
                        </h4>
                    {% endfor %}
                </div>

                {#            image#}

                <form method="post" id="rate_{{ product.3 }}" action="{% url 'accounts:rate' product.4 2 %}">
                    {% csrf_token %}
                    <input type="number" name="rate" min="0" max="5">
                    <input type="submit" name="submit">
                </form>

                <div id="product_rate">
                    {{ product.7 }}
                </div>


            </div>
        {% endfor %}
    </div>
{% endblock %}

accounts/templates/accounts/cart.html
{% extends 'base/base.html' %}

{% block title %}
    shopping cart
{% endblock %}

{% block content %}

    {% for item in items %}
        <div class="{{ item.3 }}">

            <div>
                {#                name#}
                {{ item.0 }}
            </div>
            <div>
                {#            price#}
                {{ item.1 }}
            </div>
            <div>
                {#            requested quantity#}
                {{ item.2 }}
            </div>

            <form action="{% url 'accounts:cart_delete' item.4 %}" method="post" id="{{ item.3 }}">
                {% csrf_token %}
                <input type="submit" name="submit">
            </form>
        </div>
    {% endfor %}

    <div id="total_price">
        {{ total_price }}
    </div>

    <form action="" method="post" id="pay_cart">


    </form>
{% endblock %}

accounts/templates/accounts/create-item.html
{% extends 'base/base.html' %}

{% block title %}
    create item
{% endblock %}


{% block content %}
    <h2>create item</h2>

    <form method="post" id="make_product" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {#            <input type="{{ field.type }}" name="{{ field.name }}" id="{{ field.name }}">#}

                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}
        <button type="submit">Sign up</button>


        {% if form.errors %}
            <div id="errors" style="color: #03a9f4">

                {#                {% if form.errors.username %}#}
                {#                    <p>نام کاربری شما در سیستم موجود است</p>#}
                {#                {% endif %}#}
                {##}
                {#                {% if form.errors.password2 %}#}
                {#                    <p>گذرواژه و تکرار گذرواژه یکسان نیستند</p>#}
                {#                {% endif %}#}
                {{ form.errors }}
            </div>
        {% endif %}
    </form>

{% endblock %}

accounts/templates/accounts/edit_product.html
{% extends 'base/base.html' %}
{% block title %}
    edit product
{% endblock %}


{% block content %}
    <form method="post" id="edit_product" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {#            <input type="{{ field.type }}" name="{{ field.name }}" id="{{ field.name }}">#}

                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}
        <button type="submit">edit product</button>


        {% if form.errors %}
            <div id="errors" style="color: #03a9f4">
                {{ form.errors }}
            </div>
        {% endif %}
    </form>
{% endblock %}

accounts/templates/accounts/enitre_products.html
{% extends 'base/base.html' %}


{% block title %}
    all products
{% endblock %}

{% block content %}

    <div id="error">
        {% if messages %}{% for message in messages %}{{ message }}{% endfor %}{% endif %}
    </div>




    <form method="post" id="search_products">
        {% csrf_token %}
        <input type="text" name="title">
        <input type="number" name="min_price">
        <input type="number" name="max_price">
        <input type="text" name="tag">
        <button type="submit" name="submit">submit</button>
    </form>

    <form action="{% url 'accounts:order' %}" method="post" id="order_products">
        {% csrf_token %}
        <select name="order_type" id="order_type">
            <option value="username" name="username">seller username</option>
            <option value="price" name="price">price</option>
            <option value="rate" name="rate">rate</option>
        </select>

        <select name="order" id="order">
            <option value="asc" name="asc">asc</option>
            <option value="desc" name="desc">desc</option>
        </select>
        <button name="submit" type="submit">order</button>
    </form>


    <div id="all_products">
        {% for product in products %}
            {#            class name#}

            <div class="{{ product.3 }}">
                <form action="{% url 'accounts:cart' product.4 %}" method="post" id="cart_{{ product.3 }}">
                    {% csrf_token %}
                    <input type="number" min="1" name="quantity">
                    <input type="submit" name="submit">
                </form>
                <img src="{{ product.8 }}" id="product_image_{{ product.3 }}" name="product_image_{{ product.3 }}">

                <a href="{% url 'accounts:edit' product.4 %}" id="edit_{{ product.3 }}">edit</a>
                <a href="{% url 'accounts:product_page' product.4 %}" id="{{ product.3 }}">go to product</a>
                <a href="{% url 'accounts:delete_product' product.4 %}" id="delete_{{ product.3 }}">delete</a>
                {#            name#}
                <h4>{{ product.0 }}</h4>
                <div>
                    {#                    price#}
                    {{ product.1 }}
                </div>
                <div>
                    {#                    quentity#}
                    {{ product.2 }}
                </div>
                {#                first_name#}
                <div>

                </div>
                {{ product.5 }}
                {#                last name#}
                <div>
                    {{ product.6 }}

                </div>
                <div>
                    {% for tag in product.7 %}
                        <h4>
                            {{ tag.name }}
                        </h4>
                    {% endfor %}
                </div>

                {#            image#}


                <form method="post" id="rate_{{ product.3 }}" action="{% url 'accounts:rate' product.4 1 %}">
                    {% csrf_token %}
                    <input type="number" name="rate" min="0" max="5">
                    <input type="submit" name="submit">
                </form>

                <div id="product_rate">
                    {{ product.9 }}
                </div>

            </div>
        {% endfor %}
    </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base/base.html' %}


{% block title %}
    login
{% endblock %}

{% load static %}

{% block additional %}
    <link rel="stylesheet" href="{% static 'css/LoginStyle.css"' %}"/>
{% endblock %}



{% block content %}

    <h2>Login Page</h2>
    <form id="login_form" method="post" action="{% url 'accounts:login' %}">
        {% csrf_token %}
        <div class="Box">
            <div class="inputBox">
                <input type="text" name="username" required="">
                <label>Username</label>
            </div>
            <div class="inputBox">
                <input type="password" name="password" required="">
                <label>Password</label>
            </div>
            <input type="hidden" name="next" value="{{ next }}">

            <input type="submit" name="submit" value="submit">
        </div>
    </form>

    <div id="errors">
        {% if form.errors %}
            {#                {{ form.errors }}#}
            <p>username or password wrong. try again</p>
        {% endif %}
    </div>


{% endblock %}

accounts/templates/accounts/panel.html
{% extends 'base/base.html' %}

{% block title %}
    panel
{% endblock %}


{% block content %}
    {% if is_seller %}
        <div>
            <a id="make_new_product" href="{% url 'accounts:create_item' %}">create item</a>
        </div>

        <div>
            <a href="{% url 'accounts:all_products' %}" id="my_products">go to your products </a>
        </div>
    {% endif %}

    <div>
        <form id="become_seller" method="post">
            {% csrf_token %}
            <input type="submit"> become seller </input>
        </form>


        {% if has_msg %}
            {% if become_seller %}
                <div id="done">
                    <p>با موفقیت فروشنده شدید</p>
                </div>
            {% else %}
                <div id="error">
                    <p>شما فروشنده هستید</p>
                </div>
            {% endif %}
        {% endif %}


    </div>

{% endblock %}

accounts/templates/accounts/product_page.html
{% extends 'base/base.html' %}

{% block title %}
    product page
{% endblock %}


{% block content %}
    <h4 id="name">{{ product.name }}</h4>
    <div id="quantity">{{ product.quantity }}</div>
    <div id="price">{{ product.price }}</div>
    <div id="seller_name">{{ product.user.first_name }}</div>
    <div id="seller_family">{{ product.user.last_name }}</div>


    <img src="{{ product_image_url }}" alt="image" id="product_image">

    <div id="comments">
        {% for commnet in comments %}
            <div>
                <div>
                    {{ comment.user.first_name }}
                    {{ commnet.user.last_name }}
                </div>
            <div>
                {{ commnet.text }}
            </div>

            </div>
        {% endfor %}

    </div>

    {% if user.is_authenticated %}
        <form id="write_comment" method="post">
            {% csrf_token %}
            <textarea name="text"></textarea>
            <input type="submit">
        </form>
    {% endif %}


{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base/base.html' %}

{% block title %}
    signup
{% endblock %}


{% block content %}
    <h2>Sign up</h2>

    <form method="post" id="register_form">
        {% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {#            <input type="{{ field.type }}" name="{{ field.name }}" id="{{ field.name }}">#}

                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}
        <button name="submit" type="submit">Sign up</button>


        {% if form.errors %}
            <div id="errors" style="color: #03a9f4">

                {% if form.errors.username %}
                    <p>نام کاربری شما در سیستم موجود است</p>
                {% endif %}

                {% if form.errors.password2 %}
                    <p>گذرواژه و تکرار گذرواژه یکسان نیستند</p>
                {% endif %}
                {#                {{ form.errors }}#}
            </div>
        {% endif %}
    </form>

{% endblock %}